//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigBot.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(LocalDB)\\v11.0")]
        public string OldString {
            get {
                return ((string)(this["OldString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(LocalDB)\\MSSQLLocalDB")]
        public string NewString {
            get {
                return ((string)(this["NewString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>C:\LPLADesktop\WOW\LifePortraits\LPESDatabase.config</string>
  <string>C:\LPLADesktop\WOW\LifePortraits\PlanDatabase.config</string>
  <string>C:\LPLADesktop\WOW\LifePortraits\SessionDatabase.config</string>
  <string>C:\Program Files (x86)\WoodmenLife\Woodmen Illustration Service\WOW.WoodmenIntegrationService.exe.config</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TargetFiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TargetFiles"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>LifeManagerService - WOW</string>
  <string>LifePortraitsWebServer - WOW</string>
  <string>WoodmenIntegrationService</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ServiceNames {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ServiceNames"]));
            }
        }
    }
}
