//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LpaDataFix.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=database type=mssql;server=(LocalDB)\\v11.0;database=WOWLPES;AttachDBF" +
            "ilename=C:\\LPLADesktop\\WOW\\Databases\\WOWLPES.mdf;Integrated Security=SSPI")]
        public string LpaConnectionString {
            get {
                return ((string)(this["LpaConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("insert into dbo.Scenario select [ScenarioID], null, null,[ProspectID],17,null,4,n" +
            "ull from [dbo].[ScenePointer] where [ScenarioID] not in (select [ScenarioID] fro" +
            "m [dbo].[Scenario])")]
        public string SqlQuery {
            get {
                return ((string)(this["SqlQuery"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LifePortraitsWebServer - WOW")]
        public string LpaServiceName {
            get {
                return ((string)(this["LpaServiceName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LifeManagerService - WOW")]
        public string LpaSyncServiceName {
            get {
                return ((string)(this["LpaSyncServiceName"]));
            }
        }
    }
}
