//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonIllustrationServiceTester.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:51781/api/Illustrations/ProcessIllusRequest")]
        public string IllustrationsLocalWebServiceUrl {
            get {
                return ((string)(this["IllustrationsLocalWebServiceUrl"]));
            }
            set {
                this["IllustrationsLocalWebServiceUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:05")]
        public global::System.TimeSpan WebCallDelay {
            get {
                return ((global::System.TimeSpan)(this["WebCallDelay"]));
            }
            set {
                this["WebCallDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int WebCallRetries {
            get {
                return ((int)(this["WebCallRetries"]));
            }
            set {
                this["WebCallRetries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://lpamw-test.woodmen.net/CIS/api/illustrations/ProcessIllusRequest")]
        public string IllustrationsTestWebServiceUrl {
            get {
                return ((string)(this["IllustrationsTestWebServiceUrl"]));
            }
            set {
                this["IllustrationsTestWebServiceUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://lpamw-uat.woodmen.net/CIS/api/illustrations/ProcessIllusRequest")]
        public string IllustrationsUatWebServiceUrl {
            get {
                return ((string)(this["IllustrationsUatWebServiceUrl"]));
            }
            set {
                this["IllustrationsUatWebServiceUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Temp\\")]
        public string IulOutputDirectory {
            get {
                return ((string)(this["IulOutputDirectory"]));
            }
            set {
                this["IulOutputDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://lpamw-modl.woodmen.net/CIS/api/illustrations/ProcessIllusRequest")]
        public string IllustrationsModlWebServiceUrl {
            get {
                return ((string)(this["IllustrationsModlWebServiceUrl"]));
            }
            set {
                this["IllustrationsModlWebServiceUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://lpamw.woodmen.net/CIS/api/Illustrations/ProcessIllusRequest")]
        public string IllustrationsProdWebServiceUrl {
            get {
                return ((string)(this["IllustrationsProdWebServiceUrl"]));
            }
            set {
                this["IllustrationsProdWebServiceUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://lpamw-int.woodmen.net/CIS/api/illustrations/ProcessIllusRequest")]
        public string IllustrationsIntWebServiceUrl {
            get {
                return ((string)(this["IllustrationsIntWebServiceUrl"]));
            }
            set {
                this["IllustrationsIntWebServiceUrl"] = value;
            }
        }
    }
}
