//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOW.ISU.DeltaBot.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:2015/api/Service/DatabaseCheck")]
        public string ServiceCheckUrl {
            get {
                return ((string)(this["ServiceCheckUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SOFTWARE\\StoneRiver\\ACL\\WOW")]
        public string LifePortraitsRegKeyPath {
            get {
                return ((string)(this["LifePortraitsRegKeyPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ApplicationPath")]
        public string LifePortraitsRegKeyName {
            get {
                return ((string)(this["LifePortraitsRegKeyName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WOW\\Launcher\\LifePortraits.Desktop.Client.exe,WOW\\Launcher\\LifePortraits.Desktop." +
            "WebServer.exe,WOW\\LifeManager\\LifeManager.Agent\\Life.Manager.Agent.exe,WOW\\LifeM" +
            "anager\\LifeManager.Service\\Life.Manager.Service.exe")]
        public string LifePortraitsExePaths {
            get {
                return ((string)(this["LifePortraitsExePaths"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14400000")]
        public int MigrationUtilityTimeOut {
            get {
                return ((int)(this["MigrationUtilityTimeOut"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WoodmenIntegrationService")]
        public string WoodmenIllustrationServiceName {
            get {
                return ((string)(this["WoodmenIllustrationServiceName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WOW\\LifePortraits\\bin\\ConvertIEWToAccelerate.exe")]
        public string MigrationUtilityRelativePath {
            get {
                return ((string)(this["MigrationUtilityRelativePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8C1AE857C98E8ECE12A0CA90C03961F6")]
        public string PureEdgeIfxHash {
            get {
                return ((string)(this["PureEdgeIfxHash"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\PureEdge\\Viewer 6.4\\extensions\\WoodmenIllustrationIFX.jar")]
        public string PureEdgeIfxPath {
            get {
                return ((string)(this["PureEdgeIfxPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\WiseServer\\WiseServer.exe")]
        public string WiseServerExePath {
            get {
                return ((string)(this["WiseServerExePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.00")]
        public string WiseServerExeFileVersion {
            get {
                return ((string)(this["WiseServerExeFileVersion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://lifeportraits.mywoodmen.org")]
        public string ConnectivityCheckUrl {
            get {
                return ((string)(this["ConnectivityCheckUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\Program Files\\WoodmenLife Menu\\WoodmenLife Menu.exe.config")]
        public string MainMenuConfigPath {
            get {
                return ((string)(this["MainMenuConfigPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WOW\\Launcher\\LifePortraits.Desktop.Client.exe")]
        public string LifePortraitsLauncherPath {
            get {
                return ((string)(this["LifePortraitsLauncherPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\SavedIllustrations")]
        public string IllustrationSavePath {
            get {
                return ((string)(this["IllustrationSavePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"C:\Users\All Users\Microsoft\Windows\Start Menu\WoodmenLife\Cancer Rates.LNK,C:\Users\All Users\Microsoft\Windows\Start Menu\WoodmenLife\FamilyTermQuickRates.lnk,C:\Users\All Users\Microsoft\Windows\Start Menu\WoodmenLife\Illustration Edge - 32 bit.lnk,C:\Users\All Users\Microsoft\Windows\Start Menu\WoodmenLife\Illustrations_Run_Once.lnk,C:\Users\All Users\Microsoft\Windows\Start Menu\WoodmenLife\Life Rate.lnk,C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Cancer Rates\Cancer Rates.LNK,C:\ProgramData\Microsoft\Windows\Start Menu\WoodmenLife\Cancer Rates.LNK,C:\ProgramData\Microsoft\Windows\Start Menu\WoodmenLife\FamilyTermQuickRates.lnk,C:\ProgramData\Microsoft\Windows\Start Menu\WoodmenLife\Illustration Edge - 32 bit.lnk,C:\ProgramData\Microsoft\Windows\Start Menu\WoodmenLife\Illustrations_Run_Once.lnk,C:\ProgramData\Microsoft\Windows\Start Menu\WoodmenLife\Life Rate.lnk,C:\ProgramData\Microsoft\Windows\Start Menu\WoodmenLife\Field IEW Rates.lnk,C:\Users\Public\Desktop\LifeManager Agent - WOW.lnk,C:\Users\Public\Desktop\LifePortraits Desktop System - WOW.lnk")]
        public string FilesToRemove {
            get {
                return ((string)(this["FilesToRemove"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FamilyTermQuickRates,IndependenceRate,Life Rates,RateCheck,Solution,LifeRate")]
        public string AppsToUninstall {
            get {
                return ((string)(this["AppsToUninstall"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Installation_Logs")]
        public string LoggingFolderPath {
            get {
                return ((string)(this["LoggingFolderPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Not used")]
        public string SyncAgentShortcutPath {
            get {
                return ((string)(this["SyncAgentShortcutPath"]));
            }
        }
    }
}
