//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCaseService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Work\\\\tfs_dev\\\\WOW.Illustration\\\\1_DEVL\\\\WebApps\\\\WebServiceTestManager\\\\App_" +
            "Data\\\\MobileRaterTests")]
        public string FolderPath {
            get {
                return ((string)(this["FolderPath"]));
            }
            set {
                this["FolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Work\\\\tfs_dev\\\\WOW.Illustration\\\\1_DEVL\\\\WebApps\\\\WebServiceTestManager\\\\App_" +
            "Data\\\\checkfolder")]
        public string CheckFolderPath {
            get {
                return ((string)(this["CheckFolderPath"]));
            }
            set {
                this["CheckFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"metadata=res://*/Models.RaterDB.csdl|res://*/Models.RaterDB.ssdl|res://*/Models.RaterDB.msl;provider=System.Data.SqlClient;provider connection string=""data source=(LocalDB)\MSSQLLocalDB;attachdbfilename=|DataDirectory|\TestManagerData.mdf;integrated security=True;multipleactiveresultsets=True;connect timeout=30;application name=EntityFramework""")]
        public string TestManagerDataEntities {
            get {
                return ((string)(this["TestManagerDataEntities"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("api/Rate/FetchIndependenceSeriesRates")]
        public string IndependenceSeriesEndpoint {
            get {
                return ((string)(this["IndependenceSeriesEndpoint"]));
            }
            set {
                this["IndependenceSeriesEndpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("api/Rate/FetchPatriotSeriesRate")]
        public string PatriotSeriesEndpoint {
            get {
                return ((string)(this["PatriotSeriesEndpoint"]));
            }
            set {
                this["PatriotSeriesEndpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("api/Rate/FetchFamilyTermRates")]
        public string FamilyTermEndpoint {
            get {
                return ((string)(this["FamilyTermEndpoint"]));
            }
            set {
                this["FamilyTermEndpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("api/Rate/FetchLifeRates")]
        public string LifeRaterEndpoint {
            get {
                return ((string)(this["LifeRaterEndpoint"]));
            }
            set {
                this["LifeRaterEndpoint"] = value;
            }
        }
    }
}
