//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductPremiumCollector.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MobileRaterServiceEntities : DbContext
    {
        public MobileRaterServiceEntities()
            : base("name=MobileRaterServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ProductQuote> ProductQuotes { get; set; }
    
        public virtual int PurgeProductQuotes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PurgeProductQuotes");
        }
    }
}
