//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOW.WoodmenIllustrationService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sa_lpa")]
        public string LpaBatchUsername {
            get {
                return ((string)(this["LpaBatchUsername"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("w00dm3nLP@")]
        public string LpaBatchPassword {
            get {
                return ((string)(this["LpaBatchPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~/App_Data/uploads")]
        public string UploadStorageFolder {
            get {
                return ((string)(this["UploadStorageFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~/App_Data/payloads")]
        public string PayloadStorageFolder {
            get {
                return ((string)(this["PayloadStorageFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("payload")]
        public string PayloadFileExtension {
            get {
                return ((string)(this["PayloadFileExtension"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int SqlCommandTimeout {
            get {
                return ((int)(this["SqlCommandTimeout"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string DistributionChannelName {
            get {
                return ((string)(this["DistributionChannelName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LogAcordMessages {
            get {
                return ((bool)(this["LogAcordMessages"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LogWimMessages {
            get {
                return ((bool)(this["LogWimMessages"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("850,855,860,865,870,875")]
        public string HeaderCodesWithSuppressedDues {
            get {
                return ((string)(this["HeaderCodesWithSuppressedDues"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("850,855,860,865,870,875,880,885")]
        public string Term2016HeaderCodes {
            get {
                return ((string)(this["Term2016HeaderCodes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Connection Timeout=60;Data Source=(localdb)\\WIS_Instance;Initial Catalog=WOWInteg" +
            "ration;Integrated Security=True;AttachDbFileName=|DataDirectory|\\WOWIntegration." +
            "mdf;")]
        public string IntegrationDbConnectionString {
            get {
                return ((string)(this["IntegrationDbConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BasicHttpBinding_IGatewayService")]
        public string WcfGatewayServiceClientName {
            get {
                return ((string)(this["WcfGatewayServiceClientName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BasicHttpBinding_IPersonSceneSearchService")]
        public string WcfSearchServiceClientName {
            get {
                return ((string)(this["WcfSearchServiceClientName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("123,124,280,281,282,283,284,290,291,292,293,294,295,296,297,298,850,855,860,865,8" +
            "70,875,880,885")]
        public string BackDateHeaderCodes {
            get {
                return ((string)(this["BackDateHeaderCodes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://eim-test.woodmen.net/FRHierarchyRESTService/api/v2/Hierarchy2/GetAgent?FR" +
            "Code=")]
        public string FRHierarchyServiceEndpoint {
            get {
                return ((string)(this["FRHierarchyServiceEndpoint"]));
            }
        }
    }
}
