//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOW.WoodmenReconService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReconReportDataItem
    {
        public int Id { get; set; }
        public int ReconReportId { get; set; }
        public string DataName { get; set; }
        public string DataValue { get; set; }
    
        public virtual ReconReport ReconReport { get; set; }
    }
}
