//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOW.WoodmenReconService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReconReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReconReport()
        {
            this.ReconReportDataItems = new HashSet<ReconReportDataItem>();
        }
    
        public int Id { get; set; }
        public string Hostname { get; set; }
        public System.DateTime DateReceived { get; set; }
        public string ReportName { get; set; }
        public System.DateTime DateCreatedUtc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReconReportDataItem> ReconReportDataItems { get; set; }
    }
}
