//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOW.WoodmenReconService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WoodmenReconServiceEntities : DbContext
    {
        public WoodmenReconServiceEntities()
            : base("name=WoodmenReconServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ReconReportDataItem> ReconReportDataItems { get; set; }
        public virtual DbSet<ReconReport> ReconReports { get; set; }
    
        public virtual ObjectResult<FetchNonCompliantHosts_Result> FetchNonCompliantHosts(string lpaVersionNumber, Nullable<System.DateTime> deploymentDate)
        {
            var lpaVersionNumberParameter = lpaVersionNumber != null ?
                new ObjectParameter("LpaVersionNumber", lpaVersionNumber) :
                new ObjectParameter("LpaVersionNumber", typeof(string));
    
            var deploymentDateParameter = deploymentDate.HasValue ?
                new ObjectParameter("DeploymentDate", deploymentDate) :
                new ObjectParameter("DeploymentDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FetchNonCompliantHosts_Result>("FetchNonCompliantHosts", lpaVersionNumberParameter, deploymentDateParameter);
        }
    
        public virtual ObjectResult<FetchReportsByHostname_Result> FetchReportsByHostname(string hostname, string dataName)
        {
            var hostnameParameter = hostname != null ?
                new ObjectParameter("Hostname", hostname) :
                new ObjectParameter("Hostname", typeof(string));
    
            var dataNameParameter = dataName != null ?
                new ObjectParameter("DataName", dataName) :
                new ObjectParameter("DataName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FetchReportsByHostname_Result>("FetchReportsByHostname", hostnameParameter, dataNameParameter);
        }
    }
}
