//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOW.MobileRaterService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvailabilityTable
    {
        public int CombinationID { get; set; }
        public int HeaderCode { get; set; }
        public int StateGroupId { get; set; }
        public int MinInsuredAge { get; set; }
        public int MaxInsuredAge { get; set; }
        public Nullable<bool> IsTobaccoUser { get; set; }
        public int MinRatingClass { get; set; }
        public int MaxRatingClass { get; set; }
        public int MinFaceAmount { get; set; }
        public int MaxFaceAmount { get; set; }
        public string Gender { get; set; }
        public bool IsWorkplace { get; set; }
        public string BillingMethod { get; set; }
        public string BillingMode { get; set; }
        public Nullable<bool> IsAIO { get; set; }
        public Nullable<int> MinAIOAmount { get; set; }
        public Nullable<int> MaxAIOAmount { get; set; }
        public Nullable<int> AWPRating { get; set; }
        public Nullable<int> MinPayorAge { get; set; }
        public Nullable<int> MaxPayorAge { get; set; }
        public Nullable<int> ADRating { get; set; }
        public Nullable<int> WPRating { get; set; }
        public Nullable<int> WMDRating { get; set; }
    
        public virtual BaseRating BaseRating { get; set; }
        public virtual BaseRating BaseRating1 { get; set; }
        public virtual BillingMode BillingMode1 { get; set; }
        public virtual BillingMethod BillingMethod1 { get; set; }
        public virtual RiderRating RiderRating { get; set; }
        public virtual RiderRating RiderRating1 { get; set; }
        public virtual RiderRating RiderRating2 { get; set; }
        public virtual RiderRating RiderRating3 { get; set; }
        public virtual StateGroup StateGroup { get; set; }
    }
}
