//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOW.MobileRaterService.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MobileRaterServiceEntities : DbContext
    {
        public MobileRaterServiceEntities()
            : base("name=MobileRaterServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AvailabilityTable> AvailabilityTables { get; set; }
        public virtual DbSet<BaseRating> BaseRatings { get; set; }
        public virtual DbSet<BillingMethod> BillingMethods { get; set; }
        public virtual DbSet<BillingMode> BillingModes { get; set; }
        public virtual DbSet<RaterBillingOption> RaterBillingOptions { get; set; }
        public virtual DbSet<RiderRating> RiderRatings { get; set; }
        public virtual DbSet<StateGroupMap> StateGroupMaps { get; set; }
        public virtual DbSet<StateGroup> StateGroups { get; set; }
        public virtual DbSet<StateSetting> StateSettings { get; set; }
        public virtual DbSet<SupportedPlan> SupportedPlans { get; set; }
        public virtual DbSet<ProductQuote> ProductQuotes { get; set; }
    
        public virtual ObjectResult<FetchAvaliableProducts_Result> FetchAvaliableProducts(string stateCode, Nullable<int> headerCode, Nullable<int> insuredAge, Nullable<bool> isTobaccoUser, Nullable<int> faceAmount, string billingMethod, string billingMode, Nullable<bool> isWorkplace, string gender, Nullable<int> baseRating, Nullable<System.DateTime> queryDate)
        {
            var stateCodeParameter = stateCode != null ?
                new ObjectParameter("StateCode", stateCode) :
                new ObjectParameter("StateCode", typeof(string));
    
            var headerCodeParameter = headerCode.HasValue ?
                new ObjectParameter("HeaderCode", headerCode) :
                new ObjectParameter("HeaderCode", typeof(int));
    
            var insuredAgeParameter = insuredAge.HasValue ?
                new ObjectParameter("InsuredAge", insuredAge) :
                new ObjectParameter("InsuredAge", typeof(int));
    
            var isTobaccoUserParameter = isTobaccoUser.HasValue ?
                new ObjectParameter("IsTobaccoUser", isTobaccoUser) :
                new ObjectParameter("IsTobaccoUser", typeof(bool));
    
            var faceAmountParameter = faceAmount.HasValue ?
                new ObjectParameter("FaceAmount", faceAmount) :
                new ObjectParameter("FaceAmount", typeof(int));
    
            var billingMethodParameter = billingMethod != null ?
                new ObjectParameter("BillingMethod", billingMethod) :
                new ObjectParameter("BillingMethod", typeof(string));
    
            var billingModeParameter = billingMode != null ?
                new ObjectParameter("BillingMode", billingMode) :
                new ObjectParameter("BillingMode", typeof(string));
    
            var isWorkplaceParameter = isWorkplace.HasValue ?
                new ObjectParameter("IsWorkplace", isWorkplace) :
                new ObjectParameter("IsWorkplace", typeof(bool));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            var baseRatingParameter = baseRating.HasValue ?
                new ObjectParameter("BaseRating", baseRating) :
                new ObjectParameter("BaseRating", typeof(int));
    
            var queryDateParameter = queryDate.HasValue ?
                new ObjectParameter("QueryDate", queryDate) :
                new ObjectParameter("QueryDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FetchAvaliableProducts_Result>("FetchAvaliableProducts", stateCodeParameter, headerCodeParameter, insuredAgeParameter, isTobaccoUserParameter, faceAmountParameter, billingMethodParameter, billingModeParameter, isWorkplaceParameter, genderParameter, baseRatingParameter, queryDateParameter);
        }
    
        public virtual ObjectResult<FetchReverseProducts_Result> FetchReverseProducts(Nullable<decimal> maxMonthlyPremium, Nullable<decimal> minMontlyPremium, string gender, Nullable<int> age, Nullable<bool> tabacco, Nullable<bool> aioGir, Nullable<decimal> faceAmount)
        {
            var maxMonthlyPremiumParameter = maxMonthlyPremium.HasValue ?
                new ObjectParameter("MaxMonthlyPremium", maxMonthlyPremium) :
                new ObjectParameter("MaxMonthlyPremium", typeof(decimal));
    
            var minMontlyPremiumParameter = minMontlyPremium.HasValue ?
                new ObjectParameter("MinMontlyPremium", minMontlyPremium) :
                new ObjectParameter("MinMontlyPremium", typeof(decimal));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            var ageParameter = age.HasValue ?
                new ObjectParameter("Age", age) :
                new ObjectParameter("Age", typeof(int));
    
            var tabaccoParameter = tabacco.HasValue ?
                new ObjectParameter("Tabacco", tabacco) :
                new ObjectParameter("Tabacco", typeof(bool));
    
            var aioGirParameter = aioGir.HasValue ?
                new ObjectParameter("AioGir", aioGir) :
                new ObjectParameter("AioGir", typeof(bool));
    
            var faceAmountParameter = faceAmount.HasValue ?
                new ObjectParameter("FaceAmount", faceAmount) :
                new ObjectParameter("FaceAmount", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FetchReverseProducts_Result>("FetchReverseProducts", maxMonthlyPremiumParameter, minMontlyPremiumParameter, genderParameter, ageParameter, tabaccoParameter, aioGirParameter, faceAmountParameter);
        }
    
        public virtual int PurgeProductQuotes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PurgeProductQuotes");
        }
    }
}
