//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOW.MobileRaterService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductQuote
    {
        public int ID { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        public bool Tobacco { get; set; }
        public decimal FaceAmount { get; set; }
        public string PaymentMode { get; set; }
        public string BillType { get; set; }
        public decimal Quote { get; set; }
        public System.DateTime DateCalculated { get; set; }
        public string ProductName { get; set; }
        public bool AioGir { get; set; }
    }
}
