//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOW.MobileRaterService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaterBillingOption
    {
        public int ID { get; set; }
        public string Rater { get; set; }
        public string BillTypeCode { get; set; }
        public string BillTypeName { get; set; }
        public string PremiumModeCode { get; set; }
        public string PremiumModeName { get; set; }
    }
}
