//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOW.MobileRaterService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateSetting
    {
        public string StateCode { get; set; }
        public string StateName { get; set; }
        public string StateAbbreviation { get; set; }
        public int MaxWaiverPremiumAge { get; set; }
        public int MaxApplicantWaiverPremiumAge { get; set; }
        public int MaxWaiverMonthlyDeductionAge { get; set; }
        public int MaxFamilyTermWaiverAge { get; set; }
        public int MaxAcceleratedDeathBenefitAge { get; set; }
    }
}
