//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOW.MobileRaterService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportedPlan
    {
        public int ID { get; set; }
        public string Rater { get; set; }
        public int HeaderCode { get; set; }
        public string InsuranceType { get; set; }
        public string PlanId { get; set; }
        public int Duration { get; set; }
        public string DisplayName { get; set; }
        public bool HasEmbeddedDues { get; set; }
        public decimal FaceAmount { get; set; }
    }
}
