//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LpaUpdater.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SOFTWARE\\WOW6432Node\\StoneRiver\\ACL\\WOW")]
        public string LifePortraitsRegKeyPath {
            get {
                return ((string)(this["LifePortraitsRegKeyPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ApplicationPath")]
        public string LifePortraitsRegKeyName {
            get {
                return ((string)(this["LifePortraitsRegKeyName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Installation_Logs")]
        public string LoggingFolderPath {
            get {
                return ((string)(this["LoggingFolderPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LifeManagerService - WOW")]
        public string LifeManagerServiceName {
            get {
                return ((string)(this["LifeManagerServiceName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LifePortraitsWebServer - WOW")]
        public string LifePortraitsServiceName {
            get {
                return ((string)(this["LifePortraitsServiceName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.146.5990.68006")]
        public string NewLpaVersionNumber {
            get {
                return ((string)(this["NewLpaVersionNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.143.5990.68006")]
        public string TargetLpaVersionNumber {
            get {
                return ((string)(this["TargetLpaVersionNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WOW\\Databases\\WOWPlans.mdf")]
        public string PlansDatabasePath {
            get {
                return ((string)(this["PlansDatabasePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WOW\\LifePortraits\\bin\\system.ver")]
        public string VersionFilePath {
            get {
                return ((string)(this["VersionFilePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WOW\\LifeManager\\LifeManager.Service\\UAB\\applications")]
        public string RsuApplicationsFolderPath {
            get {
                return ((string)(this["RsuApplicationsFolderPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WOW\\LifeManager\\LifeManager.Service\\UAB\\downloader")]
        public string RsuDownloadFolderPath {
            get {
                return ((string)(this["RsuDownloadFolderPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WOW\\LifeManager\\LifeManager.Service\\UAB")]
        public string RsuRegistryFolderPath {
            get {
                return ((string)(this["RsuRegistryFolderPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=database type=mssql;server=(LocalDB)\\v11.0;database=WOWPlans;AttachDB" +
            "Filename=C:\\LPLADesktop\\WOW\\Databases\\WOWPlans.mdf;Integrated Security=SSPI")]
        public string LpaConnectionString {
            get {
                return ((string)(this["LpaConnectionString"]));
            }
        }
    }
}
