//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LpaUpdater.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlCommands {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlCommands() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LpaUpdater.Properties.SqlCommands", typeof(SqlCommands).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///--Start changes for table RateData
        ///
        ///UPDATE [RateData] SET 
        ///[RateDataID]=17976, 
        ///[RateCode]=6011, 
        ///[Age]=0, 
        ///[Sex]=2, 
        ///[Class]=1, 
        ///[Band]=1, 
        ///[Rate1]=3.3, 
        ///[Rate2]=0, 
        ///[Rate3]=0, 
        ///[Rate4]=0, 
        ///[Rate5]=0, 
        ///[Rate6]=0, 
        ///[Rate7]=0, 
        ///[Rate8]=0, 
        ///[Rate9]=0, 
        ///[Rate10]=0
        /// WHERE [RateDataID]=17976;
        ///
        ///
        ///UPDATE [RateData] SET 
        ///[RateDataID]=17977, 
        ///[RateCode]=6012, 
        ///[Age]=0, 
        ///[Sex]=2, 
        ///[Class]=1, 
        ///[Band]=1, 
        ///[Rate1]=3.3, 
        ///[Rate2]=0, 
        ///[Rate3]=0, 
        ///[Rate4]=0, 
        ///[Rate5]=0, 
        ///[Rate6]=0, 
        ///[Rate [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string March2019AnnuityUpdate {
            get {
                return ResourceManager.GetString("March2019AnnuityUpdate", resourceCulture);
            }
        }
    }
}
