//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOW.LifePortraitsWebAuthentication.AgentAccountServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wwww/stoneriver.com/services/AgentAccountService", ConfigurationName="AgentAccountServiceReference.IAgentAccountService")]
    public interface IAgentAccountService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wwww/stoneriver.com/services/AgentAccountService/IAgentAccountService/agen" +
            "tSetup", ReplyAction="http://wwww/stoneriver.com/services/AgentAccountService/IAgentAccountService/agen" +
            "tSetupResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LifeServer.DataModel.request.AgentAccountCreatorRequest))]
        LifeServer.DataModel.response.AgentAccountResponse agentSetup(LifeServer.DataModel.request.AgentAccountRequest requestObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wwww/stoneriver.com/services/AgentAccountService/IAgentAccountService/agen" +
            "tSetup", ReplyAction="http://wwww/stoneriver.com/services/AgentAccountService/IAgentAccountService/agen" +
            "tSetupResponse")]
        System.Threading.Tasks.Task<LifeServer.DataModel.response.AgentAccountResponse> agentSetupAsync(LifeServer.DataModel.request.AgentAccountRequest requestObject);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAgentAccountServiceChannel : WOW.LifePortraitsWebAuthentication.AgentAccountServiceReference.IAgentAccountService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AgentAccountServiceClient : System.ServiceModel.ClientBase<WOW.LifePortraitsWebAuthentication.AgentAccountServiceReference.IAgentAccountService>, WOW.LifePortraitsWebAuthentication.AgentAccountServiceReference.IAgentAccountService {
        
        public AgentAccountServiceClient() {
        }
        
        public AgentAccountServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AgentAccountServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgentAccountServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgentAccountServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LifeServer.DataModel.response.AgentAccountResponse agentSetup(LifeServer.DataModel.request.AgentAccountRequest requestObject) {
            return base.Channel.agentSetup(requestObject);
        }
        
        public System.Threading.Tasks.Task<LifeServer.DataModel.response.AgentAccountResponse> agentSetupAsync(LifeServer.DataModel.request.AgentAccountRequest requestObject) {
            return base.Channel.agentSetupAsync(requestObject);
        }
    }
}
