//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOW.Illustration.Utilities.ValuesOutputComparer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WOW.Illustration.Utilities.ValuesOutputComparer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Source Directory.
        /// </summary>
        internal static string BrowseFolderDescription {
            get {
                return ResourceManager.GetString("BrowseFolderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Compare to load.
        /// </summary>
        internal static string DefaultDifferenceItem {
            get {
                return ResourceManager.GetString("DefaultDifferenceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (NONE).
        /// </summary>
        internal static string DefaultFileName {
            get {
                return ResourceManager.GetString("DefaultFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory not found: {0}.
        /// </summary>
        internal static string InvalidDirectoryMessage {
            get {
                return ResourceManager.GetString("InvalidDirectoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Values Files.
        /// </summary>
        internal static string InvalidDirectoryTitle {
            get {
                return ResourceManager.GetString("InvalidDirectoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No differences found..
        /// </summary>
        internal static string NoDifferencesMessage {
            get {
                return ResourceManager.GetString("NoDifferencesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PE File Compare.
        /// </summary>
        internal static string NoDifferencesTitle {
            get {
                return ResourceManager.GetString("NoDifferencesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Search16 {
            get {
                object obj = ResourceManager.GetObject("Search16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
