//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOW.WoodmenIllustrationService.LpaGatewayService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LifeServerBaseRequest", Namespace="http://schemas.datacontract.org/2004/07/LifeServer.DataModel.request")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WOW.WoodmenIllustrationService.LpaGatewayService.AgentAccountRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WOW.WoodmenIllustrationService.LpaGatewayService.AgentAccountCreatorRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WOW.WoodmenIllustrationService.LpaGatewayService.AccountSetupRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WOW.WoodmenIllustrationService.LpaGatewayService.TxLifeServiceRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WOW.WoodmenIllustrationService.LpaGatewayService.GatewayServiceRequest))]
    public partial class LifeServerBaseRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgentAccountRequest", Namespace="http://schemas.datacontract.org/2004/07/LifeServer.DataModel.request")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WOW.WoodmenIllustrationService.LpaGatewayService.AgentAccountCreatorRequest))]
    public partial class AgentAccountRequest : WOW.WoodmenIllustrationService.LpaGatewayService.LifeServerBaseRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Xml.XmlElement accountSetupRequestXMLField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Xml.XmlElement accountSetupRequestXML {
            get {
                return this.accountSetupRequestXMLField;
            }
            set {
                if ((object.ReferenceEquals(this.accountSetupRequestXMLField, value) != true)) {
                    this.accountSetupRequestXMLField = value;
                    this.RaisePropertyChanged("accountSetupRequestXML");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgentAccountCreatorRequest", Namespace="http://schemas.datacontract.org/2004/07/LifeServer.DataModel.request")]
    [System.SerializableAttribute()]
    public partial class AgentAccountCreatorRequest : WOW.WoodmenIllustrationService.LpaGatewayService.AgentAccountRequest {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountSetupRequest", Namespace="http://schemas.datacontract.org/2004/07/LifeServer.DataModel.request")]
    [System.SerializableAttribute()]
    public partial class AccountSetupRequest : WOW.WoodmenIllustrationService.LpaGatewayService.LifeServerBaseRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Xml.XmlElement GatewayServiceXMLElementField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Xml.XmlElement GatewayServiceXMLElement {
            get {
                return this.GatewayServiceXMLElementField;
            }
            set {
                if ((object.ReferenceEquals(this.GatewayServiceXMLElementField, value) != true)) {
                    this.GatewayServiceXMLElementField = value;
                    this.RaisePropertyChanged("GatewayServiceXMLElement");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TxLifeServiceRequest", Namespace="")]
    [System.SerializableAttribute()]
    public partial class TxLifeServiceRequest : WOW.WoodmenIllustrationService.LpaGatewayService.LifeServerBaseRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid SceneIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Xml.XmlElement xmlDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SceneID {
            get {
                return this.SceneIDField;
            }
            set {
                if ((this.SceneIDField.Equals(value) != true)) {
                    this.SceneIDField = value;
                    this.RaisePropertyChanged("SceneID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Xml.XmlElement xmlData {
            get {
                return this.xmlDataField;
            }
            set {
                if ((object.ReferenceEquals(this.xmlDataField, value) != true)) {
                    this.xmlDataField = value;
                    this.RaisePropertyChanged("xmlData");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GatewayServiceRequest", Namespace="http://schemas.datacontract.org/2004/07/LifeServer.DataModel.request")]
    [System.SerializableAttribute()]
    public partial class GatewayServiceRequest : WOW.WoodmenIllustrationService.LpaGatewayService.LifeServerBaseRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Xml.XmlElement GatewayServiceXMLElementField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Xml.XmlElement GatewayServiceXMLElement {
            get {
                return this.GatewayServiceXMLElementField;
            }
            set {
                if ((object.ReferenceEquals(this.GatewayServiceXMLElementField, value) != true)) {
                    this.GatewayServiceXMLElementField = value;
                    this.RaisePropertyChanged("GatewayServiceXMLElement");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LifeServerBaseResponse", Namespace="http://schemas.datacontract.org/2004/07/LifeServer.DataModel")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WOW.WoodmenIllustrationService.LpaGatewayService.TxLifeServiceResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WOW.WoodmenIllustrationService.LpaGatewayService.AgentAccountResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WOW.WoodmenIllustrationService.LpaGatewayService.AccountSetupResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WOW.WoodmenIllustrationService.LpaGatewayService.LoginResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WOW.WoodmenIllustrationService.LpaGatewayService.GatewayServiceResponse))]
    public partial class LifeServerBaseResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WOW.WoodmenIllustrationService.LpaGatewayService.LifeServerException ExceptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WOW.WoodmenIllustrationService.LpaGatewayService.LifeServerException Exception {
            get {
                return this.ExceptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionField, value) != true)) {
                    this.ExceptionField = value;
                    this.RaisePropertyChanged("Exception");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasError {
            get {
                return this.HasErrorField;
            }
            set {
                if ((this.HasErrorField.Equals(value) != true)) {
                    this.HasErrorField = value;
                    this.RaisePropertyChanged("HasError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LifeServerException", Namespace="http://schemas.datacontract.org/2004/07/LifeServer.DataModel")]
    [System.SerializableAttribute()]
    public partial class LifeServerException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OccurenceDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OccurenceDateTime {
            get {
                return this.OccurenceDateTimeField;
            }
            set {
                if ((this.OccurenceDateTimeField.Equals(value) != true)) {
                    this.OccurenceDateTimeField = value;
                    this.RaisePropertyChanged("OccurenceDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TxLifeServiceResponse", Namespace="")]
    [System.SerializableAttribute()]
    public partial class TxLifeServiceResponse : WOW.WoodmenIllustrationService.LpaGatewayService.LifeServerBaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Xml.XmlElement txLifeResponseXMLField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Xml.XmlElement txLifeResponseXML {
            get {
                return this.txLifeResponseXMLField;
            }
            set {
                if ((object.ReferenceEquals(this.txLifeResponseXMLField, value) != true)) {
                    this.txLifeResponseXMLField = value;
                    this.RaisePropertyChanged("txLifeResponseXML");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgentAccountResponse", Namespace="http://schemas.datacontract.org/2004/07/LifeServer.DataModel.response")]
    [System.SerializableAttribute()]
    public partial class AgentAccountResponse : WOW.WoodmenIllustrationService.LpaGatewayService.LifeServerBaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Xml.XmlElement accountCreateResponseXMLField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Xml.XmlElement accountCreateResponseXML {
            get {
                return this.accountCreateResponseXMLField;
            }
            set {
                if ((object.ReferenceEquals(this.accountCreateResponseXMLField, value) != true)) {
                    this.accountCreateResponseXMLField = value;
                    this.RaisePropertyChanged("accountCreateResponseXML");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountSetupResponse", Namespace="http://schemas.datacontract.org/2004/07/LifeServer.DataModel.response")]
    [System.SerializableAttribute()]
    public partial class AccountSetupResponse : WOW.WoodmenIllustrationService.LpaGatewayService.LifeServerBaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Xml.XmlElement AccountSetupResponseElementField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Xml.XmlElement AccountSetupResponseElement {
            get {
                return this.AccountSetupResponseElementField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountSetupResponseElementField, value) != true)) {
                    this.AccountSetupResponseElementField = value;
                    this.RaisePropertyChanged("AccountSetupResponseElement");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResponse", Namespace="http://schemas.datacontract.org/2004/07/LifeServer.DataModel.response")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WOW.WoodmenIllustrationService.LpaGatewayService.AgentAccountCreatorRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WOW.WoodmenIllustrationService.LpaGatewayService.AgentAccountRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WOW.WoodmenIllustrationService.LpaGatewayService.LifeServerBaseRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WOW.WoodmenIllustrationService.LpaGatewayService.AccountSetupRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WOW.WoodmenIllustrationService.LpaGatewayService.GatewayServiceRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WOW.WoodmenIllustrationService.LpaGatewayService.LifeServerBaseResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WOW.WoodmenIllustrationService.LpaGatewayService.LifeServerException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WOW.WoodmenIllustrationService.LpaGatewayService.TxLifeServiceResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WOW.WoodmenIllustrationService.LpaGatewayService.TxLifeServiceRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WOW.WoodmenIllustrationService.LpaGatewayService.AgentAccountResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WOW.WoodmenIllustrationService.LpaGatewayService.AccountSetupResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WOW.WoodmenIllustrationService.LpaGatewayService.GatewayServiceResponse))]
    public partial class LoginResponse : WOW.WoodmenIllustrationService.LpaGatewayService.LifeServerBaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object UserInformationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object UserInformation {
            get {
                return this.UserInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.UserInformationField, value) != true)) {
                    this.UserInformationField = value;
                    this.RaisePropertyChanged("UserInformation");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GatewayServiceResponse", Namespace="http://schemas.datacontract.org/2004/07/LifeServer.DataModel.response")]
    [System.SerializableAttribute()]
    public partial class GatewayServiceResponse : WOW.WoodmenIllustrationService.LpaGatewayService.LifeServerBaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Xml.XmlElement GetwayServiceResponseElementField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Xml.XmlElement GetwayServiceResponseElement {
            get {
                return this.GetwayServiceResponseElementField;
            }
            set {
                if ((object.ReferenceEquals(this.GetwayServiceResponseElementField, value) != true)) {
                    this.GetwayServiceResponseElementField = value;
                    this.RaisePropertyChanged("GetwayServiceResponseElement");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wwww/stoneriver.com/services/GatewayService", ConfigurationName="LpaGatewayService.IGatewayService")]
    public interface IGatewayService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wwww/stoneriver.com/services/GatewayService/IGatewayService/processXmlRequ" +
            "est", ReplyAction="http://wwww/stoneriver.com/services/GatewayService/IGatewayService/processXmlRequ" +
            "estResponse")]
        System.Xml.XmlElement processXmlRequest(System.Xml.XmlElement request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wwww/stoneriver.com/services/GatewayService/IGatewayService/processXmlRequ" +
            "est", ReplyAction="http://wwww/stoneriver.com/services/GatewayService/IGatewayService/processXmlRequ" +
            "estResponse")]
        System.Threading.Tasks.Task<System.Xml.XmlElement> processXmlRequestAsync(System.Xml.XmlElement request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wwww/stoneriver.com/services/GatewayService/IGatewayService/processRequest" +
            "", ReplyAction="http://wwww/stoneriver.com/services/GatewayService/IGatewayService/processRequest" +
            "Response")]
        WOW.WoodmenIllustrationService.LpaGatewayService.GatewayServiceResponse processRequest(WOW.WoodmenIllustrationService.LpaGatewayService.GatewayServiceRequest requestObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wwww/stoneriver.com/services/GatewayService/IGatewayService/processRequest" +
            "", ReplyAction="http://wwww/stoneriver.com/services/GatewayService/IGatewayService/processRequest" +
            "Response")]
        System.Threading.Tasks.Task<WOW.WoodmenIllustrationService.LpaGatewayService.GatewayServiceResponse> processRequestAsync(WOW.WoodmenIllustrationService.LpaGatewayService.GatewayServiceRequest requestObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wwww/stoneriver.com/services/GatewayService/IGatewayService/processStringR" +
            "equest", ReplyAction="http://wwww/stoneriver.com/services/GatewayService/IGatewayService/processStringR" +
            "equestResponse")]
        string processStringRequest(string request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wwww/stoneriver.com/services/GatewayService/IGatewayService/processStringR" +
            "equest", ReplyAction="http://wwww/stoneriver.com/services/GatewayService/IGatewayService/processStringR" +
            "equestResponse")]
        System.Threading.Tasks.Task<string> processStringRequestAsync(string request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGatewayServiceChannel : WOW.WoodmenIllustrationService.LpaGatewayService.IGatewayService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GatewayServiceClient : System.ServiceModel.ClientBase<WOW.WoodmenIllustrationService.LpaGatewayService.IGatewayService>, WOW.WoodmenIllustrationService.LpaGatewayService.IGatewayService {
        
        public GatewayServiceClient() {
        }
        
        public GatewayServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GatewayServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GatewayServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GatewayServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Xml.XmlElement processXmlRequest(System.Xml.XmlElement request) {
            return base.Channel.processXmlRequest(request);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlElement> processXmlRequestAsync(System.Xml.XmlElement request) {
            return base.Channel.processXmlRequestAsync(request);
        }
        
        public WOW.WoodmenIllustrationService.LpaGatewayService.GatewayServiceResponse processRequest(WOW.WoodmenIllustrationService.LpaGatewayService.GatewayServiceRequest requestObject) {
            return base.Channel.processRequest(requestObject);
        }
        
        public System.Threading.Tasks.Task<WOW.WoodmenIllustrationService.LpaGatewayService.GatewayServiceResponse> processRequestAsync(WOW.WoodmenIllustrationService.LpaGatewayService.GatewayServiceRequest requestObject) {
            return base.Channel.processRequestAsync(requestObject);
        }
        
        public string processStringRequest(string request) {
            return base.Channel.processStringRequest(request);
        }
        
        public System.Threading.Tasks.Task<string> processStringRequestAsync(string request) {
            return base.Channel.processStringRequestAsync(request);
        }
    }
}
