//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceTestManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Database : DbContext
    {
        public Database()
            : base("name=Database")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<TestSet> TestSets { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserTestSet> UserTestSets { get; set; }
        public virtual DbSet<UserDestination> UserDestinations { get; set; }
        public virtual DbSet<ExpectedValue> ExpectedValues { get; set; }
        public virtual DbSet<TestExecution> TestExecutions { get; set; }
        public virtual DbSet<Destination> Destinations { get; set; }
    
        public virtual ObjectResult<FetchTestSetsByUser_Result> FetchTestSetsByUser(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FetchTestSetsByUser_Result>("FetchTestSetsByUser", userIdParameter);
        }
    
        public virtual ObjectResult<FetchDestinationsByUser_Result> FetchDestinationsByUser(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FetchDestinationsByUser_Result>("FetchDestinationsByUser", userIdParameter);
        }
    }
}
