//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceTestManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpectedValue
    {
        public System.Guid Id { get; set; }
        public System.Guid FileId { get; set; }
        public string PropertyName { get; set; }
        public string ExpectedResult { get; set; }
        public int Type { get; set; }
    
        public virtual File File { get; set; }
    }
}
