//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceTestManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestExecution
    {
        public int Id { get; set; }
        public System.Guid FileId { get; set; }
        public string TestSetName { get; set; }
        public string DestinationName { get; set; }
        public string DestinationUrl { get; set; }
        public int TestSetId { get; set; }
        public int Result { get; set; }
        public System.DateTime ExecutionDate { get; set; }
        public System.Guid TestIdentifier { get; set; }
        public string Summary { get; set; }
    }
}
