//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LpaDataFix.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LifePortraitsWebServer - WOW")]
        public string LpaServiceName {
            get {
                return ((string)(this["LpaServiceName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LifeManagerService - WOW")]
        public string LpaSyncServiceName {
            get {
                return ((string)(this["LpaSyncServiceName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"DECLARE @state int; DECLARE @mode int; select top 1 @state = ApplicationState from [dbo].[Scenario] WHERE ApplicationState IS NOT NULL GROUP BY ApplicationState ORDER BY COUNT(ApplicationState) DESC; select top 1 @mode = PremiumMode from [dbo].[Scenario] WHERE PremiumMode IS NOT NULL GROUP BY PremiumMode ORDER BY COUNT(PremiumMode) DESC; insert into dbo.Scenario select [ScenarioID], null, null, [ProspectID], @state, null, @mode, null from [dbo].[ScenePointer] where [ScenarioID] not in (select [ScenarioID] from [dbo].[Scenario]);")]
        public string SqlQuery {
            get {
                return ((string)(this["SqlQuery"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"DECLARE @NullScenario TABLE (SceneID UNIQUEIDENTIFIER, NewGuid UNIQUEIDENTIFIER);INSERT INTO @NullScenario SELECT [SceneID], NEWID() as NewGuid FROM [ScenePointer] where typecode = 32 and ScenarioID is null; Insert into [Scenario] ([ScenarioID],[OwnerType],[OrgOwnerID],[PersonOwnerID],[ApplicationState],[EffectiveDate],[PremiumMode],[SignedDate]) Select NewGuid, 1, null, null, 17, null, 1, null from @NullScenario; Update sp Set sp.ScenarioID = ns.NewGuid from [ScenePointer] sp inner join @NullScenario ns on sp.SceneID = ns.SceneID;")]
        public string ObjRefSql {
            get {
                return ((string)(this["ObjRefSql"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;Initial Catalog=WOWLPES;AttachDBFilename=C:\\\\LPLADesk" +
            "top\\\\WOW\\\\Databases\\\\WOWLPES.mdf;Integrated Security=True")]
        public string LpaConnectionString {
            get {
                return ((string)(this["LpaConnectionString"]));
            }
        }
    }
}
