//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.CommonIllustrationService.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasePlan
    {
        public string PlanId { get; set; }
        public int HeaderCode { get; set; }
        public string Description { get; set; }
    
        public virtual HeaderCode HeaderCode1 { get; set; }
    }
}
