//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.CommonIllustrationService.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conversion
    {
        public string ConversionId { get; set; }
        public string CommonVal { get; set; }
        public string LpaVal { get; set; }
        public System.DateTime start { get; set; }
        public System.DateTime expiration { get; set; }
    
        public virtual ConversionId ConversionId1 { get; set; }
    }
}
