//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.CommonIllustrationService.DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IllusWisEntities : DbContext
    {
        public IllusWisEntities()
            : base("name=IllusWisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BasePlan> BasePlans { get; set; }
        public virtual DbSet<ConversionId> ConversionIds { get; set; }
        public virtual DbSet<Conversion> Conversions { get; set; }
        public virtual DbSet<HeaderCode> HeaderCodes { get; set; }
        public virtual DbSet<StateCode> StateCodes { get; set; }
    }
}
