//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.CommonIllustrationService.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateCode
    {
        public short Code { get; set; }
        public string Name { get; set; }
        public string Abbr { get; set; }
        public bool NAIC { get; set; }
        public bool IsUnisex { get; set; }
        public bool PrintAsTobacco { get; set; }
        public short Max_Waiver_Age { get; set; }
    }
}
