//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResetUpdates.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\LPLADesktop\\WOW\\LifePortraits\\bin\\system.ver")]
        public string VersionFilePath {
            get {
                return ((string)(this["VersionFilePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\LPLADesktop\\WOW\\LifeManager\\LifeManager.Service\\UAB\\registry")]
        public string RsuRegistryFolderPath {
            get {
                return ((string)(this["RsuRegistryFolderPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\LPLADesktop\\WOW\\LifeManager\\LifeManager.Service\\UAB\\downloader")]
        public string RsuDownloadFolderPath {
            get {
                return ((string)(this["RsuDownloadFolderPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\LPLADesktop\\WOW\\LifeManager\\LifeManager.Service\\UAB\\applications")]
        public string RsuApplicationsFolderPath {
            get {
                return ((string)(this["RsuApplicationsFolderPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LifeManagerService - WOW")]
        public string LifeManagerServiceName {
            get {
                return ((string)(this["LifeManagerServiceName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LifePortraitsWebServer - WOW")]
        public string LifePortraitsServiceName {
            get {
                return ((string)(this["LifePortraitsServiceName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Windows\\System32\\config\\systemprofile\\AppData\\Local\\Microsoft\\Microsoft SQL Se" +
            "rver Local DB\\Instances")]
        public string LocalDbInstancesFolderPath {
            get {
                return ((string)(this["LocalDbInstancesFolderPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ResetUpdatesTool.log")]
        public string LogFilePath {
            get {
                return ((string)(this["LogFilePath"]));
            }
        }
    }
}
