//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOW.WoodmenIllustrationService.LpaSearchService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wwww/stoneriver.com/services/PersonSceneSearchService", ConfigurationName="LpaSearchService.IPersonSceneSearchService")]
    public interface IPersonSceneSearchService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wwww/stoneriver.com/services/PersonSceneSearchService/IPersonSceneSearchSe" +
            "rvice/processXmlRequest", ReplyAction="http://wwww/stoneriver.com/services/PersonSceneSearchService/IPersonSceneSearchSe" +
            "rvice/processXmlRequestResponse")]
        System.Xml.XmlElement processXmlRequest(System.Xml.XmlElement request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wwww/stoneriver.com/services/PersonSceneSearchService/IPersonSceneSearchSe" +
            "rvice/processXmlRequest", ReplyAction="http://wwww/stoneriver.com/services/PersonSceneSearchService/IPersonSceneSearchSe" +
            "rvice/processXmlRequestResponse")]
        System.Threading.Tasks.Task<System.Xml.XmlElement> processXmlRequestAsync(System.Xml.XmlElement request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wwww/stoneriver.com/services/PersonSceneSearchService/IPersonSceneSearchSe" +
            "rvice/processRequest", ReplyAction="http://wwww/stoneriver.com/services/PersonSceneSearchService/IPersonSceneSearchSe" +
            "rvice/processRequestResponse")]
        string processRequest(string request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wwww/stoneriver.com/services/PersonSceneSearchService/IPersonSceneSearchSe" +
            "rvice/processRequest", ReplyAction="http://wwww/stoneriver.com/services/PersonSceneSearchService/IPersonSceneSearchSe" +
            "rvice/processRequestResponse")]
        System.Threading.Tasks.Task<string> processRequestAsync(string request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPersonSceneSearchServiceChannel : WOW.WoodmenIllustrationService.LpaSearchService.IPersonSceneSearchService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonSceneSearchServiceClient : System.ServiceModel.ClientBase<WOW.WoodmenIllustrationService.LpaSearchService.IPersonSceneSearchService>, WOW.WoodmenIllustrationService.LpaSearchService.IPersonSceneSearchService {
        
        public PersonSceneSearchServiceClient() {
        }
        
        public PersonSceneSearchServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonSceneSearchServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonSceneSearchServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonSceneSearchServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Xml.XmlElement processXmlRequest(System.Xml.XmlElement request) {
            return base.Channel.processXmlRequest(request);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlElement> processXmlRequestAsync(System.Xml.XmlElement request) {
            return base.Channel.processXmlRequestAsync(request);
        }
        
        public string processRequest(string request) {
            return base.Channel.processRequest(request);
        }
        
        public System.Threading.Tasks.Task<string> processRequestAsync(string request) {
            return base.Channel.processRequestAsync(request);
        }
    }
}
